name: Update VSCode Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string

jobs:
  update-ggshield-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VSCode extension repo
        uses: actions/checkout@v4
        with:
          repository: GitGuardian/gitguardian-vscode
          token: ${{ secrets.PAT_GITHUB }}
          sparse-checkout: |
            ggshield_version
          sparse-checkout-cone-mode: false

      - name: Create branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b update-ggshield-to-${{ inputs.version }}

      - name: Update ggshield_version file
        run: |
          version="${{ inputs.version }}"
          version="${version#v}"  # Remove leading 'v' if present
          echo "$version" > ggshield_version

      - name: Commit changes
        run: |
          git add ggshield_version
          git commit -m "Update ggshield version to ${{ inputs.version }}"

      - name: Push changes
        run: |
          git push --set-upstream origin update-ggshield-to-${{ inputs.version }} --force

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh pr create \
            --repo GitGuardian/gitguardian-vscode \
            --title "Update ggshield version to ${{ inputs.version }}" \
            --body "This PR updates the bundled ggshield CLI to version ${{ inputs.version }}. This update was automatically generated by a worflow on ggshield repository." \
            --base main \
            --head update-ggshield-to-${{ inputs.version }}
